"""Ajout des abonnements

Revision ID: 1774af27cbab
Revises: 8322f7a9f490
Create Date: 2022-02-09 15:48:51.456672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1774af27cbab'
down_revision = '8322f7a9f490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnements',
    sa.Column('abonne_id', sa.Integer(), nullable=True),
    sa.Column('abonnement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abonne_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['abonnement_id'], ['user.id'], ),
    sa.UniqueConstraint('abonne_id', 'abonnement_id', name='unicite_couple')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abonnements')
    # ### end Alembic commands ###
